
FROM maven:3.8.4-openjdk-17-slim AS build
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: Crea la imagen final de la aplicación
FROM openjdk:17-jdk-slim
COPY --from=build target/dockerized.postgresql-0.0.1-SNAPSHOT.jar java-app.jar
EXPOSE 8080
CMD ["java", "-jar", "java-app.jar"]